
"""
dump_globals.py
===============

WARNING: This file was generated by AI Qwen3.8-Max!

GDB Python script: extracts global variables from an ELF (C language),
recursively expands struct/union fields, and prints:

    name|type|address|size

Filtered out: arrays of structs/unions/pointers, pointers, const variables.
For arrays, SIZE is the size of one element.

Type names are fixed-width (int32_t, float64_t, ...) derived from the actual
bit width, taking target byte size into account.

Partially known structures (TYPE_CODE_ERROR) are recovered on a best-effort
basis via 'info types' and 'ptype /o'.

Compatible with GDB 7.x+ (no gdb.Type.unsigned, no f-strings).

Usage:
    gdb -nx -batch -iex "set auto-load no" -x dump_globals.py ./program.elf
"""

import gdb
import sys
import re
import struct


# ==============================================================================
#  Constants
# ==============================================================================

_EM_TI_C2000 = (140, 141)          # ELF e_machine values for C2000

INT_BITS = {
    8:  ("int8_t",   "uint8_t"),
    16: ("int16_t",  "uint16_t"),
    32: ("int32_t",  "uint32_t"),
    64: ("int64_t",  "uint64_t"),
}

FLT_BITS = {
    16:  "float16_t",
    32:  "float32_t",
    64:  "float64_t",
    128: "float128_t",
}

_TYPE_KEYWORDS = {
    "volatile", "const", "restrict", "struct", "union", "enum",
    "unsigned", "signed", "short", "long", "char", "int",
    "float", "double", "void", "_Bool",
}

_SKIP_PREFIXES = ("File ", "Non-debugging", "All defined", "0x")

_PTYPE_FIELD_RE = re.compile(
    r"/\*\s*(\d+)(?:\s*:\s*\d+)?\s*\|\s*\d+\s*\*/\s*"
    r"(.+?)\s+"
    r"(\w+(?:\[[^\]]*\])*)"
    r"(?:\s*:\s*\d+)?"
    r"\s*;")


# ==============================================================================
#  Target byte size
# ==============================================================================

_TARGET_CHAR_BITS = None


def _elf_machine(filename):
    """Read e_machine from an ELF header. Returns int or None."""
    try:
        with open(filename, "rb") as f:
            ident = f.read(16)
            if len(ident) < 16 or ident[:4] != b"\x7fELF":
                return None
            endian = "<" if ident[5] == 1 else ">"
            f.seek(18)
            raw = f.read(2)
            return struct.unpack(endian + "H", raw)[0] if len(raw) == 2 else None
    except Exception:
        return None


def target_char_bits():
    """Return target byte size in bits (cached). Default: 8."""
    global _TARGET_CHAR_BITS
    if _TARGET_CHAR_BITS is not None:
        return _TARGET_CHAR_BITS

    _TARGET_CHAR_BITS = 8

    # 1. Explicit GDB parameter.
    for cmd in ("show target-char-size", "maintenance show target-char-size"):
        try:
            m = re.search(r"(\d+)", gdb.execute(cmd, to_string=True))
            if m and int(m.group(1)) > 0:
                _TARGET_CHAR_BITS = int(m.group(1))
                return _TARGET_CHAR_BITS
        except Exception:
            pass

    # 2. Architecture name.
    try:
        arch = gdb.execute("show architecture", to_string=True).lower()
        if any(s in arch for s in ("c2000", "tic2x", "tms320")):
            _TARGET_CHAR_BITS = 16
            return _TARGET_CHAR_BITS
    except Exception:
        pass

    # 3. ELF header.
    try:
        for objfile in gdb.objfiles():
            if _elf_machine(objfile.filename) in _EM_TI_C2000:
                _TARGET_CHAR_BITS = 16
                return _TARGET_CHAR_BITS
    except Exception:
        pass

    return _TARGET_CHAR_BITS


# ==============================================================================
#  Type helpers
# ==============================================================================

def strip_to_base(gdb_type):
    """Remove typedefs and qualifiers; return the base type. Never raises."""
    try:
        t = gdb_type.unqualified()
    except Exception:
        return gdb_type
    try:
        stripped = t.strip_typedefs()
        # Do not unqualified() structs/unions: it may degrade them to error.
        if stripped.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
            return stripped
        stripped = stripped.unqualified()
        if stripped.code != gdb.TYPE_CODE_ERROR:
            return stripped
    except Exception:
        pass
    return t


def has_const(gdb_type):
    """Return True if the type is const-qualified. Never raises."""
    try:
        return "const" in str(gdb_type.strip_typedefs())
    except Exception:
        try:
            return "const" in str(gdb_type)
        except Exception:
            return False


def is_pointer(gdb_type):
    """Return True if the type is a pointer (typedefs resolved)."""
    return strip_to_base(gdb_type).code == gdb.TYPE_CODE_PTR


def type_size(gdb_type):
    """Return sizeof in target bytes, or None on failure."""
    try:
        return strip_to_base(gdb_type).sizeof
    except Exception:
        return None


def base_type_name(gdb_type):
    """Return a fixed-width type name (e.g. int32_t, float64_t)."""
    t = strip_to_base(gdb_type)
    code = t.code

    try:
        bits = t.sizeof * target_char_bits()
    except Exception:
        bits = None

    if code in (gdb.TYPE_CODE_INT, gdb.TYPE_CODE_CHAR):
        try:
            unsigned = "unsigned" in str(t)
        except Exception:
            unsigned = False
        if bits in INT_BITS:
            return INT_BITS[bits][1] if unsigned else INT_BITS[bits][0]
        if bits is not None:
            return ("uint{}_t" if unsigned else "int{}_t").format(bits)

    if code == gdb.TYPE_CODE_FLT:
        if bits in FLT_BITS:
            return FLT_BITS[bits]
        if bits is not None:
            return "float{}_t".format(bits)

    if code == gdb.TYPE_CODE_ENUM:
        try:
            fields = t.fields()
            if fields:
                return base_type_name(fields[0].type)
        except Exception:
            pass
        return "int32_t"

    if code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
        tag = t.tag or "<anonymous>"
        kind = "struct" if code == gdb.TYPE_CODE_STRUCT else "union"
        return "{} {}".format(kind, tag)

    return str(t)


# ==============================================================================
#  Array helpers
# ==============================================================================

def array_dimensions(gdb_type):
    """Return (dims, elem_type) for a possibly multi-dimensional array."""
    dims = []
    t = strip_to_base(gdb_type)
    while t.code == gdb.TYPE_CODE_ARRAY:
        try:
            low, high = t.range()
            dims.append(high - low + 1)
        except Exception:
            dims.append("?")
        try:
            t = strip_to_base(t.target())
        except Exception:
            break
    return dims, t


def is_filtered_array(gdb_type):
    """Return True for arrays of structs / unions / pointers."""
    dims, elem = array_dimensions(gdb_type)
    return bool(dims) and elem.code in (
        gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION, gdb.TYPE_CODE_PTR)


# ==============================================================================
#  Fallback helpers for partially known types
# ==============================================================================

_INFO_TYPES_CACHE = {}


def _fields_from_ptype(spec):
    """Parse 'ptype /o <spec>' output into (offset, type_str, name) tuples."""
    try:
        raw = gdb.execute("ptype /o {}".format(spec), to_string=True)
    except Exception:
        return []
    fields = []
    for line in raw.splitlines():
        m = _PTYPE_FIELD_RE.search(line)
        if m:
            fields.append((int(m.group(1)), m.group(2).strip(), m.group(3).strip()))
    return fields


def _type_names_from_info_types(pattern):
    """Extract type names from 'info types <pattern>' (cached)."""
    if pattern in _INFO_TYPES_CACHE:
        return _INFO_TYPES_CACHE[pattern]
    try:
        raw = gdb.execute("info types {}".format(pattern), to_string=True)
    except Exception:
        _INFO_TYPES_CACHE[pattern] = []
        return []

    names = []
    for line in raw.splitlines():
        m = re.match(r"\s*\d+:\s*(.+);$", line.strip())
        if m:
            tokens = re.findall(r"\w+", m.group(1))
            if tokens:
                names.append(tokens[-1])

    seen = set()
    unique = []
    for n in names:
        if n not in seen:
            seen.add(n)
            unique.append(n)

    _INFO_TYPES_CACHE[pattern] = unique
    return unique


def _extract_tag(gdb_type):
    """Extract a plausible type name from a gdb.Type (or None)."""
    tag = getattr(gdb_type, "tag", None)
    if tag:
        return tag

    type_str = str(gdb_type)
    if "<unknown" in type_str:
        return None

    m = re.search(r"\b(?:struct|union)\s+(\w+)", type_str)
    if m:
        return m.group(1)

    words = [w for w in re.findall(r"\w+", type_str) if w not in _TYPE_KEYWORDS]
    return words[-1] if words else None


def _expand_fields(prefix, container_type, address, depth, out):
    """Expand struct/union fields. Returns True if any field was processed."""
    try:
        fields = container_type.fields()
    except Exception:
        return False

    expanded = False
    for field in fields:
        if field.artificial or not hasattr(field, "bitpos") or field.bitpos is None:
            continue
        name = field.name or "<anonymous>"
        walk("{}.{}".format(prefix, name), field.type,
             address + field.bitpos // 8, depth + 1, out)
        expanded = True
    return expanded


def _lookup_and_expand(type_name, prefix, address, depth, out):
    """Look up a type by name; expand if it is a struct/union."""
    try:
        t = gdb.lookup_type(type_name)
    except Exception:
        return False

    if t.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
        return _expand_fields(prefix, t, address, depth, out)

    if t.code == gdb.TYPE_CODE_TYPEDEF:
        try:
            stripped = t.strip_typedefs()
            if stripped.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
                return _expand_fields(prefix, stripped, address, depth, out)
        except Exception:
            pass

    return False


def _recover_broken_type(prefix, gdb_type, t, address, depth, out):
    """Best-effort recovery for TYPE_CODE_TYPEDEF / TYPE_CODE_ERROR."""
    # 1. Strip typedef directly.
    if t.code == gdb.TYPE_CODE_TYPEDEF:
        try:
            stripped = t.strip_typedefs()
            if stripped.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
                return _expand_fields(prefix, stripped, address, depth, out)
        except Exception:
            pass

    # 2. Try fields on the type itself and the original unqualified type.
    if _expand_fields(prefix, t, address, depth, out):
        return True
    try:
        orig = gdb_type.unqualified()
    except Exception:
        orig = gdb_type
    if orig is not t and _expand_fields(prefix, orig, address, depth, out):
        return True

    # 3. Look up plausible type names.
    tag = _extract_tag(gdb_type)
    candidates = []
    if tag:
        candidates.extend(["struct " + tag, "union " + tag, tag])

    patterns = {prefix.split(".")[-1]}
    if tag:
        patterns.add(tag)
    for pat in patterns:
        candidates.extend(_type_names_from_info_types(pat))

    for name in candidates:
        if _lookup_and_expand(name, prefix, address, depth, out):
            return True

    # 4. Parse 'ptype /o' output.
    for spec in candidates + [prefix]:
        ptype_fields = _fields_from_ptype(spec)
        if not ptype_fields:
            continue
        added = False
        for offset, ftype_str, field_name in ptype_fields:
            if "const" in ftype_str:
                continue
            out.append((address + offset, ftype_str, None,
                         "{}.{}".format(prefix, field_name)))
            added = True
        if added:
            return True

    return False


# ==============================================================================
#  Recursive type walker
# ==============================================================================

def walk(prefix, gdb_type, address, depth, out):
    """
    Recursively expand a type and append entries to out.

    Entry format: (address_int, type_str, size_bytes_or_None, full_name).
    """
    if depth > 128 or has_const(gdb_type):
        return

    t = strip_to_base(gdb_type)

    # Struct / union.
    if t.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION):
        _expand_fields(prefix, t, address, depth, out)
        return

    # Typedef / error: best-effort recovery.
    if t.code in (gdb.TYPE_CODE_TYPEDEF, gdb.TYPE_CODE_ERROR):
        if _recover_broken_type(prefix, gdb_type, t, address, depth, out):
            return
        sys.stderr.write("[!] Skipping '{}': cannot resolve type ('{}')\n"
                         .format(prefix, str(gdb_type)))
        return

    # Array.
    if t.code == gdb.TYPE_CODE_ARRAY:
        dims, elem = array_dimensions(t)
        if elem.code in (gdb.TYPE_CODE_STRUCT, gdb.TYPE_CODE_UNION,
                         gdb.TYPE_CODE_PTR):
            return
        dims_str = "".join("[{}]".format(d) for d in dims)
        out.append((address, base_type_name(elem), type_size(elem),
                     "{}{}".format(prefix, dims_str)))
        return

    # Pointer.
    if t.code == gdb.TYPE_CODE_PTR:
        return

    # Scalar.
    if t.code in (gdb.TYPE_CODE_INT,  gdb.TYPE_CODE_FLT,
                  gdb.TYPE_CODE_BOOL, gdb.TYPE_CODE_CHAR,
                  gdb.TYPE_CODE_ENUM, gdb.TYPE_CODE_VOID):
        out.append((address, base_type_name(t), type_size(t), prefix))


# ==============================================================================
#  Global variable collection
# ==============================================================================

def collect_global_names():
    """Parse 'info variables' and return a set of global variable names."""
    try:
        raw = gdb.execute("info variables", to_string=True)
    except gdb.error as exc:
        sys.stderr.write("[!] 'info variables' failed: {}\n".format(exc))
        return set()

    names = set()
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith(_SKIP_PREFIXES) or ";" not in line:
            continue
        decl = line.split(";")[0].strip()
        for part in decl.split(","):
            tokens = part.strip().split()
            if not tokens:
                continue
            name = re.sub(r"\[.*", "", tokens[-1].lstrip("*")).strip()
            if name.isidentifier():
                names.add(name)
    return names


# ==============================================================================
#  Entry point
# ==============================================================================

def _process_variable(name, out):
    """Resolve one global variable and walk its type."""
    try:
        sym = gdb.lookup_global_symbol(name)
    except Exception:
        return
    if sym is None or not sym.is_variable:
        return

    try:
        value = sym.value()
    except Exception:
        return
    if value.address is None:
        return

    try:
        address = int(value.address)
    except Exception:
        return

    if (has_const(value.type)
            or is_filtered_array(value.type)
            or is_pointer(value.type)):
        return

    walk(name, value.type, address, 0, out)


def main():
    """Collect global variables, walk their types, and print the results."""
    if not gdb.objfiles():
        sys.stderr.write("[!] No ELF loaded.\n")
        return

    var_names = collect_global_names()
    if not var_names:
        sys.stderr.write("[!] No global variables found.\n")
        return

    results = []
    for name in sorted(var_names):
        _process_variable(name, results)

    for addr, type_str, size, name in results:
        size_str = str(size) if size is not None else "?"
        print("{}|{}|{}|{}".format(name, type_str, addr, size_str))


if __name__ == "__main__":
    main()
