"""
jtag_interface.py
=================

WARNING: This file was generated by AI Qwen3.8-Max!

Singleton wrapper around an OpenOCD TCL server for non-intrusive
SWD memory monitoring.

Key guarantees:
    - nRST / nTRST are NEVER asserted  (reset_config none).
    - The target core is NEVER halted by this module.
    - All memory reads go through the debug AHB-AP and do not
        interrupt firmware execution.

OpenOCD is started with:
    reset_config none → init
No 'reset init', no 'halt', no 'resume' at startup.
A conditional resume (TCL: foreach t [target names] {...}) is sent
only if the core was halted by an external tool.

Variable reading is batched: all 'mdb' commands are sent in a single
TCP packet and all responses are read in one round-trip, regardless
of variable count.  Failed reads silently produce 0.0.

Thread safety:
    _lifecycle_lock  →  process / socket create-destroy
    _io_lock         →  socket send / recv / _recv_buffer
    Lock order is always lifecycle → io, never reversed.
    Watchdog uses a separate _watchdog_lock and never holds
    lifecycle or io locks.

A daemon watchdog thread periodically calls ensure_connection(),
which recovers the session WITHOUT hardware reset:
    1. mdb health check
    2. conditional resume + re-check
    3. full OpenOCD restart (still non-intrusive)

Backward-compatible aliases are preserved:
    connect_to_port()        → connect()
    disconnect_from_port()   → disconnect()
    stop_openocd_server()    → disconnect()
    run_openocd_server()     → spawn only (no port wait)
    is_openocd_server_connected → is_server_alive()

Requires: Python 3.10+, numpy, OpenOCD ≥ 0.11 (tcl port syntax).

Usage:
    jtag = JTAG_Interface()
    jtag.adapter   = 'cmsis-dap'
    jtag.target    = 'at32f4x'
    jtag.bitrate   = '1 MHz'

    if jtag.connect():
        jtag.start_watchdog(interval=3.0)
        data = jtag.read_variables(
            addresses=[0x2000_0000, 0x2000_0004],
            types=[TYPE_FLOAT32, TYPE_UINT32],
        )
        jtag.stop_watchdog()
        jtag.disconnect()
"""

from __future__ import annotations

import atexit
import socket
import struct
import subprocess
import threading
import time
from contextlib import suppress
from typing import Self

import numpy as np

import __main__
from model.interface.build_frame import PACK_SIZE

# ======================================================================
# Constants
# ======================================================================

JTAG_BITRATE_STR_TO_INT: dict[str, int] = {
    '10 MHz': 10_000_000,
    '5 MHz': 5_000_000,
    '2 MHz': 2_000_000,
    '1 MHz': 1_000_000,
    '500 kHz': 500_000,
    '200 kHz': 200_000,
    '100 kHz': 100_000,
    '50 kHz': 50_000,
    '20 kHz': 20_000,
    '10 kHz': 10_000,
    '5 kHz': 5_000,
}

_TCL_PORT = 48950
_HEALTH_CHECK_ADDRESS = 0x08000000
_TERMINATOR = b'\x1a'
_RECV_SIZE = 4096

_CONNECT_PORT_ATTEMPTS = 50
_CONNECT_PORT_DELAY = 0.1

_TARGET_WAIT_ATTEMPTS = 20
_TARGET_WAIT_DELAY = 0.2

_RECONNECT_DELAY = 1.0
_WATCHDOG_JOIN_TIMEOUT = 2.0

_RESUME_IF_HALTED = (
    'foreach t [target names] {'
    'if {[$t curstate] eq "halted"} {$t resume}'
    '}'
)

_HEX_DIGITS = frozenset('0123456789abcdefABCDEF')


# ======================================================================
# Helpers
# ======================================================================


def _response_has_error(text: str) -> bool:
    """True if any line is an OpenOCD error ('Error', 'Error: …')."""
    for line in text.splitlines():
        s = line.strip()
        if s.startswith('Error') and (len(s) == 5 or s[5] in ': '):
            return True
    return False


def _parse_mdb_response(response: str) -> bytes:
    """Parse hex bytes from ``0x08000000: 01 02 03 04``."""
    colon = response.find(':')
    if colon == -1:
        raise ValueError(f'Invalid mdb response: {response!r}')

    payload = response[colon + 1:]

    try:
        return bytes.fromhex(payload)
    except ValueError as exc:
        raw = bytes(
            int(t, 16)
            for t in payload.split()
            if len(t) == 2 and t[0] in _HEX_DIGITS and t[1] in _HEX_DIGITS
        )
        if not raw:
            raise ValueError(
                f'No hex data in mdb response: {response!r}',
            ) from exc
        return raw


# ======================================================================
# JTAG_Interface
# ======================================================================


class JTAG_Interface:
    """
    Singleton wrapper around OpenOCD TCL server (non-intrusive mode).

    * nRST / nTRST never asserted  (``reset_config none``).
    * Core is never halted by this class.
    * Memory reads go through debug AHB-AP without stopping the CPU.
    """

    __slots__ = (
        '_adapter', '_bitrate', '_target',
        '_sock', '_process',
        '_io_lock', '_lifecycle_lock', '_watchdog_lock',
        '_watchdog_thread', '_watchdog_stop',
        '_recv_buffer', '_fast_mode', '_struct_cache',
        '_initialized',
    )

    __instance: JTAG_Interface | None = None

    # ------------------------------------------------------------------
    # Singleton
    # ------------------------------------------------------------------

    def __new__(cls) -> Self:
        if cls.__instance is None:
            cls.__instance = super().__new__(cls)
        return cls.__instance

    def __init__(self) -> None:
        if getattr(self, '_initialized', False):
            return

        self._adapter: str = ''
        self._bitrate: int = JTAG_BITRATE_STR_TO_INT['1 MHz']
        self._target: str = ''

        self._sock: socket.socket | None = None
        self._process: subprocess.Popen | None = None

        self._io_lock = threading.RLock()
        self._lifecycle_lock = threading.RLock()
        self._watchdog_lock = threading.Lock()

        self._watchdog_thread: threading.Thread | None = None
        self._watchdog_stop: threading.Event | None = None

        self._recv_buffer: bytes = b''
        self._fast_mode: bool = True
        self._struct_cache: dict[int, tuple[struct.Struct, int]] = {}

        self._initialized: bool = True
        atexit.register(self._atexit_cleanup)

    def __repr__(self) -> str:
        state = 'up' if self._sock else 'down'
        return f'<JTAG {self._adapter}/{self._target} {state}>'

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def adapter(self) -> str:
        return self._adapter

    @adapter.setter
    def adapter(self, v: str) -> None:
        self._adapter = v

    @property
    def bitrate(self) -> int:
        return self._bitrate

    @bitrate.setter
    def bitrate(self, v: str | int) -> None:
        if isinstance(v, int):
            self._bitrate = v
        else:
            try:
                self._bitrate = JTAG_BITRATE_STR_TO_INT[v]
            except KeyError as exc:
                raise ValueError(f'Unsupported bitrate: {v!r}') from exc

    @property
    def target(self) -> str:
        return self._target

    @target.setter
    def target(self, v: str) -> None:
        self._target = v

    @property
    def fast_mode(self) -> bool:
        return self._fast_mode

    @fast_mode.setter
    def fast_mode(self, v: bool) -> None:
        self._fast_mode = bool(v)

    # ------------------------------------------------------------------
    # TCL I/O
    # ------------------------------------------------------------------

    def send_command(self, cmd: str, *, check_errors: bool | None = None) -> str:
        """Send one TCL command, return its response text."""
        if check_errors is None:
            check_errors = not self._fast_mode

        text = self._send_batch([cmd])[0]

        if check_errors and _response_has_error(text):
            raise RuntimeError(text)
        return text

    def _send_batch(self, commands: list[str]) -> list[str]:
        """
        Send *commands* in a single TCP packet, read all responses.

        One network round-trip regardless of command count.
        """
        if not commands:
            return []

        with self._io_lock:
            sock = self._sock
            if sock is None:
                raise ConnectionError('OpenOCD socket is not connected')

            try:
                sock.sendall(
                    b''.join(c.encode() + _TERMINATOR for c in commands),
                )

                buf = self._recv_buffer
                self._recv_buffer = b''
                out: list[str] = []

                for _ in commands:
                    while _TERMINATOR not in buf:
                        chunk = sock.recv(_RECV_SIZE)
                        if not chunk:
                            raise ConnectionError('OpenOCD closed connection')
                        buf += chunk
                    answer, _, buf = buf.partition(_TERMINATOR)
                    out.append(answer.decode('utf-8', errors='replace').strip())

                self._recv_buffer = buf
                return out

            except OSError:
                self._sock = None
                self._recv_buffer = b''
                with suppress(OSError):
                    sock.close()
                raise

    # ------------------------------------------------------------------
    # Variable reading (non-intrusive, batch)
    # ------------------------------------------------------------------

    def read_variables(
        self,
        addresses: list[int] | tuple[int, ...],
        types: list[int] | tuple[int, ...],
    ) -> np.ndarray:
        """
        Batch-read variables via debug AHB-AP in one round-trip.
        Core keeps running.  Failed reads → 0.0.
        """
        n = len(addresses)
        result = np.zeros((n, 1), dtype=np.float64)
        result[:] = np.nan

        if n == 0:
            return result
        if len(types) != n:
            raise ValueError('addresses and types must have the same length')

        cmds: list[str] = []
        fmts: list[struct.Struct] = []
        for addr, vt in zip(addresses, types):
            fmt, size = self._get_struct(vt)
            cmds.append(f'mdb {addr:#x} {size}')
            fmts.append(fmt)

        try:
            responses = self._send_batch(cmds)
        except OSError:
            return result

        for i, (resp, fmt) in enumerate(zip(responses, fmts)):
            with suppress(ValueError, struct.error):
                result[i, 0] = fmt.unpack_from(_parse_mdb_response(resp))[0]

        return result

    # ------------------------------------------------------------------
    # Health checks
    # ------------------------------------------------------------------

    def is_server_alive(self) -> bool:
        """TCL server responds to echo."""
        try:
            self.send_command('echo ok', check_errors=False)
            return True
        except (OSError, RuntimeError):
            return False

    def is_target_accessible(self) -> bool:
        """Non-intrusive 4-byte flash read. Does not halt / reset."""
        try:
            self.send_command(
                f'mdb {_HEALTH_CHECK_ADDRESS:#x} 4', check_errors=True,
            )
            return True
        except (OSError, RuntimeError):
            return False

    def is_connected(self) -> bool:
        """Target responds to memory reads (implies server alive)."""
        return self.is_target_accessible()

    # backward compat
    is_openocd_server_connected = is_server_alive

    # ------------------------------------------------------------------
    # Connection lifecycle
    # ------------------------------------------------------------------

    def connect(self) -> bool:
        """Start OpenOCD, attach via SWD, verify target. No reset."""
        with self._lifecycle_lock:
            return self._connect_unlocked()

    def disconnect(self) -> None:
        """Resume core (if halted), close socket, kill OpenOCD."""
        with self._lifecycle_lock:
            self._teardown()

    def ensure_connection(
        self, *, allow_restart: bool = True, attempts: int = 3,
    ) -> bool:
        """
        Non-intrusive recovery: mdb check → resume → restart.
        No hardware reset at any step.
        """
        with self._lifecycle_lock:
            if self.is_target_accessible():
                return True

            if self.is_server_alive():
                self._resume_if_halted()
                if self.is_target_accessible():
                    return True

            if not allow_restart:
                return False

            for _ in range(attempts):
                time.sleep(_RECONNECT_DELAY)
                if self._connect_unlocked():
                    return True
            return False

    # backward compat aliases
    def connect_to_port(self) -> bool:
        return self.connect()

    def disconnect_from_port(self) -> bool:
        self.disconnect()
        return True

    def stop_openocd_server(self) -> None:
        self.disconnect()

    def run_openocd_server(self) -> None:
        with self._lifecycle_lock:
            self._teardown(resume=False)
            self._spawn_openocd()

    # ------------------------------------------------------------------
    # Watchdog
    # ------------------------------------------------------------------

    def start_watchdog(self, interval: float = 3.0) -> None:
        """Background monitoring. Never resets the target."""
        with self._watchdog_lock:
            if self._watchdog_thread is not None and self._watchdog_thread.is_alive():
                return
            stop = threading.Event()
            self._watchdog_stop = stop
            self._watchdog_thread = threading.Thread(
                target=self._watchdog_loop,
                args=(interval, stop),
                daemon=True,
            )
            self._watchdog_thread.start()

    def stop_watchdog(self) -> None:
        with self._watchdog_lock:
            stop, thread = self._watchdog_stop, self._watchdog_thread
            self._watchdog_stop = None
            self._watchdog_thread = None
        if stop is not None:
            stop.set()
        if thread is not None and thread.is_alive():
            thread.join(timeout=_WATCHDOG_JOIN_TIMEOUT)

    # ------------------------------------------------------------------
    # Internal: connection  (caller holds _lifecycle_lock)
    # ------------------------------------------------------------------

    def _connect_unlocked(self) -> bool:
        # Tear down old session; skip resume — we are about to reconnect.
        self._teardown(resume=False)

        try:
            self._spawn_openocd()
        except OSError:
            return False

        if not self._wait_for_port() or not self._wait_for_target():
            self._teardown(resume=False)
            return False

        # New session established — make sure the core is running.
        self._resume_if_halted()
        return True

    # ------------------------------------------------------------------
    # Internal: process
    # ------------------------------------------------------------------

    def _spawn_openocd(self) -> None:
        self._process = subprocess.Popen(
            [
                str(__main__.FULL_PATH / 'openocd' / 'openocd.exe'),
                '--debug=0',
                '-f', f'interface/{self._adapter}.cfg',
                '-c', 'transport select swd',
                '-f', f'target/{self._target}.cfg',
                '-c', f'adapter speed {self._bitrate // 1000}',
                '-c', f'tcl port {_TCL_PORT}',
                '-c', 'reset_config none',
                '-c', 'init',
            ],
            cwd=str(__main__.FULL_PATH / 'openocd'),
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NO_WINDOW,
        )

    def _kill_openocd(self) -> None:
        proc = self._process
        if proc is None:
            return

        with suppress(OSError):
            proc.terminate()
        with suppress(Exception):
            proc.wait(timeout=1)

        if proc.poll() is None:
            with suppress(OSError):
                proc.kill()
            with suppress(Exception):
                proc.wait(timeout=1)

        self._process = None

    # ------------------------------------------------------------------
    # Internal: socket
    # ------------------------------------------------------------------

    def _wait_for_port(self) -> bool:
        for _ in range(_CONNECT_PORT_ATTEMPTS):
            if self._process is not None and self._process.poll() is not None:
                return False

            try:
                sock = socket.create_connection(
                    ('127.0.0.1', _TCL_PORT), timeout=_CONNECT_PORT_DELAY,
                )
            except OSError:
                time.sleep(_CONNECT_PORT_DELAY)
                continue

            try:
                sock.settimeout(1.0)
                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            except OSError:
                with suppress(OSError):
                    sock.close()
                return False

            with self._io_lock:
                self._sock = sock
                self._recv_buffer = b''
            return True

        return False

    def _wait_for_target(self) -> bool:
        for _ in range(_TARGET_WAIT_ATTEMPTS):
            if self.is_target_accessible():
                return True
            time.sleep(_TARGET_WAIT_DELAY)
        return False

    def _close_socket(self) -> None:
        with self._io_lock:
            sock = self._sock
            self._sock = None
            self._recv_buffer = b''

        if sock is not None:
            with suppress(OSError):
                sock.shutdown(socket.SHUT_RDWR)
            with suppress(OSError):
                sock.close()

    # ------------------------------------------------------------------
    # Internal: teardown  (caller holds _lifecycle_lock)
    # ------------------------------------------------------------------

    def _teardown(self, *, resume: bool = True) -> None:
        if resume:
            self._resume_if_halted()
        self._close_socket()
        self._kill_openocd()

    # ------------------------------------------------------------------
    # Internal: target
    # ------------------------------------------------------------------

    def _resume_if_halted(self) -> None:
        """Resume only if halted; no-op on a running core."""
        with suppress(OSError, RuntimeError):
            self.send_command(_RESUME_IF_HALTED, check_errors=False)

    # ------------------------------------------------------------------
    # Internal: struct cache
    # ------------------------------------------------------------------

    def _get_struct(self, vt: int) -> tuple[struct.Struct, int]:
        cached = self._struct_cache.get(vt)
        if cached is None:
            c, sz = PACK_SIZE[vt]
            cached = (struct.Struct(f'<{c}'), sz)
            self._struct_cache[vt] = cached
        return cached

    # ------------------------------------------------------------------
    # Internal: watchdog / atexit
    # ------------------------------------------------------------------

    def _watchdog_loop(self, interval: float, stop: threading.Event) -> None:
        while not stop.wait(interval):
            self.ensure_connection()

    def _atexit_cleanup(self) -> None:
        # No _lifecycle_lock here — avoid deadlock with watchdog thread.
        stop = self._watchdog_stop
        if stop is not None:
            stop.set()
        thread = self._watchdog_thread
        if thread is not None and thread.is_alive():
            thread.join(timeout=0.5)

        with suppress(Exception):
            self._close_socket()
        with suppress(Exception):
            self._kill_openocd()